steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["artifacts", "docker", "images", "delete", "us-east1-docker.pkg.dev/postcard-368413/cloud-run-source-deploy/postcard/", "--delete-tags"]
  allowFailure: true
- name: "gcr.io/cloud-builders/gcloud"
  args: ["artifacts", "docker", "images", "delete", "us-east1-docker.pkg.dev/postcard-368413/gcf-artifacts/postcard--function/", "--delete-tags"]
  allowFailure: true
- name: "gcr.io/cloud-builders/gcloud"
  args: ["artifacts", "docker", "images", "delete", "us-east1-docker.pkg.dev/postcard-368413/gcf-artifacts/postcard--function/cache/", "--delete-tags"]
  allowFailure: true
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ["run", "build"]
  secretEnv: ['MAP_API_KEY']
  availableSecrets:
    secretManager:
    - versionName: projects/952598646239/secrets/MAPS_API_KEY/versions/latest
      env: 'MAP_API_KEY'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["storage", "rm", "--recursive", "gs://postcard.gaborcsapo.com/*"]
  allowFailure: true
- name: "gcr.io/cloud-builders/gcloud"
  args: ["storage", "cp", "--recursive", "dist/*", "gs://postcard.gaborcsapo.com"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["functions", "deploy", "postcard-function", "--region=us-east1", "--source", ".", "--trigger-http", "--runtime=nodejs16", "--allow-unauthenticated", "--entry-point=app", "--gen2"]
timeout: "1600s"